"""add description field to PhotoModel

Revision ID: 57457b32836a
Revises: 6f61e8519561
Create Date: 2024-02-07 11:12:51.032052

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '57457b32836a'
down_revision = '6f61e8519561'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('photos', schema=None) as batch_op:
        batch_op.add_column(sa.Column('description', sa.String(length=255), nullable=True))

    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('photos', schema=None) as batch_op:
        batch_op.drop_column('description')

    # ### end Alembic commands ###
